name:                retroclash-sim
version:             0.1.2
category:            Hardware, Graphics
synopsis:            High-level simulators from the book "Retrocomputing with Clash"
description: |
  A library of functionality useful when simulating retro-computers:

    * Interactive Clash simulation in IO
    
    * SDL-based framework for graphics simulation

    * VGA signal interpreter
    
homepage:            https://unsafePerform.IO/retroclash/
github:              gergoerdi/retroclash-sim
license:             MIT
author:              Gergő Érdi
maintainer:          gergo@erdi.hu
copyright:           2021 Gergő Érdi

dependencies:
  - base >= 4.14 && < 5
  - clash-prelude >= 1.4.2 && < 2.0
  - clash-lib  >= 1.4.2 && < 2.0
  - clash-ghc >= 1.4.2 && < 2.0
  - ghc-typelits-natnormalise <= 1.0
  - ghc-typelits-extra <= 1.0
  - ghc-typelits-knownnat <= 1.0

  - retroclash-lib ^>= 0.1

  - sdl2 ^>= 2.5.0.0
  - mtl < 3
  - transformers < 0.7
  - array < 0.6
  - text >= 2 && < 3
  - lens < 6
  - arrows ^>= 0.4
  
source-dirs:
  - src

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators

library:
  exposed-modules:
    - RetroClash.Sim.SDL
    - RetroClash.Sim.VGA
    - RetroClash.Sim.VGASDL
    - RetroClash.Sim.IO
